title: State Courts Practice Directions 2021
remote_theme: opendocsg/opendoc-theme@master
timezone: Asia/Singapore
repository: opendocsg/opendoc-state-courts-practice-directions-2021
plugins:
  - jekyll-include-cache
baseurl: ''
server_PROD: https://search.opendoc.sg
server_DEV: https://search.opendoc.sg
offline: false
google_analytics: UA-113717369-8

styling_options:
  primary_brand_color: '#9f0836'
  logo_path: /assets/logo-full.png
  opendoc_logo_path: /assets/images/logo-full.png
  feedback_url: https://form.gov.sg/5cee3d46138e3200109244df

hide_toolbar:
  sidebar: false
  pdf: false
  github: true

folders:
  - name: '/'
    title: 'State Courts Practice Directions 2021'
    subtitle: ''
    order:
      - 'PART-01-INTRODUCTION.md'
      - 'PART-02-GENERAL-MATTERS.md'
      - 'PART-03-ORIGINATING-PROCESSES-AND-DOCUMENTS.md'
      - 'PART-04-CASE-MANAGEMENT-AND-COURT-ALTERNATIVE-DISPUTE-RESOLUTION.md'
      - 'PART-05-DOCUMENTS-ONLY-PROCEEDINGS.md'
      - 'PART-06-INJUNCTIONS-AND-CERTAIN-OTHER-APPLICATIONS.md'
      - 'PART-07-REMOTE-HEARINGS.md'
      - 'PART-08-EVIDENCEâ€“WITNESSES-AFFIDAVITS-AND-EXHIBITS.md' 
      - 'PART-09-DOCUMENTS-AND-AUTHORITIES-FOR-USE-IN-COURT.md'
      - 'PART-10-JUDGMENTS-AND-ORDERS.md'
      - 'PART-11-FURTHER-ARGUMENTS.md'
      - 'PART-12-ELECTRONIC-FILING-SERVICE.md'
      - 'PART-13-ENFORCEMENT-MATTERS.md'
      - 'PART-14-BILLS-OF-COSTS-FOR-ASSESSMENT.md'
      - 'PART-15-DEFAMATION-ACTIONS.md'
      - 'PART-16-REFERENCE-TO-ACTUARIAL-TABLES-IN-PERSONAL-INJURY-AND-DEATH-CLAIMS.md'
      - 'PART-17-CRIMINAL-MATTERS.md'
      - 'PART-18-ELECTRONIC-FILING-AND-SERVICE-FOR-CRIMINAL-PROCEEDINGS.md'
      - 'PART-19-PROCEEDINGS-BEFORE-THE-COMMUNITY-COURTS-AND-TRIBUNALS-CLUSTER.md'
      - 'Appendices.md'
